from src.creational_patterns.factory_method.product.abstract_product import Product
from src.creational_patterns.factory_method.product.concrete_product_1 import ConcreteProduct1
from src.creational_patterns.factory_method.product.concrete_product_2 import ConcreteProduct2
