from src.structural_patterns.adapter.adapter_method import adapter_method
from src.structural_patterns.bridge.bridge import bridge_method
from src.structural_patterns.composite.composite_method import composite_method
from src.structural_patterns.decorator.decorator_method import decorator_method
from src.structural_patterns.facade.facade_method import facade_method
from src.structural_patterns.flyweigh.flyweight_method import flyweight_method
from src.structural_patterns.proxy.proxy_method import proxy_method
